# Generated by Django 6.0.1 on 2026-01-07 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, max_length=80)),
                ('services', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_name', models.CharField(max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('ussd', 'ussd'), ('whatsapp', 'whatsapp'), ('sms', 'sms'), ('voice', 'voice'), ('app', 'app')], max_length=16)),
                ('direction', models.CharField(choices=[('in', 'in'), ('out', 'out')], max_length=3)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('content', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('correlation_id', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('visit', 'visit'), ('pregnancy', 'pregnancy'), ('referral', 'referral')], max_length=16)),
                ('condition_json', models.JSONField(default=dict)),
                ('actions_json', models.JSONField(default=list)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CHV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('dob', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=32)),
                ('chronic_conditions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.household')),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_age_weeks', models.IntegerField(default=0)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('last_anc_visit', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('priority', models.CharField(choices=[('normal', 'normal'), ('urgent', 'urgent')], default='normal', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.facility')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('sms', 'sms'), ('voice', 'voice'), ('wa', 'wa')], max_length=8)),
                ('schedule_at', models.DateTimeField()),
                ('template_code', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('sent', 'sent'), ('failed', 'failed')], default='scheduled', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.chv')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('channel', models.CharField(choices=[('app', 'app'), ('ussd', 'ussd'), ('whatsapp', 'whatsapp')], default='app', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.chv')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_codes', models.JSONField(blank=True, default=list)),
                ('severity', models.IntegerField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_reports', to='core.visit')),
            ],
        ),
    ]
