# Generated by Django 6.0.1 on 2026-01-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_syncenvelope_chv_updated_at_facility_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
